### ISSUE TITLE
The released workflow does not work well.

### ISSUE THREAD

**Issue by ambjlon** [tupton/alfred-chrome-history#15]
Alfred version is v3.2

I clicked the released workflow 'alfred-chrome-history-v0.4.0.alfredworkflow' to install this workflow.
The installation was successful. But is didn't work.

However, if I installed it with symlinking the cloned directory to <sync directory>/Alfred.alfredpreferences/workflows/alfred-chrome-history, it worked well.

By the way, it seems that installing python-alfred globally is necessary, also docopt!

**Comment by Overload119** [comment]
I had a couple issues that I fixed by:

`mkdir -p "/Users/<YourFolder>/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/"`

I also upgraded the alfred.py script because I got unicode errors.

I replaced alfred.py with the latest version: https://github.com/nikipore/alfred-python/blob/master/alfred.py

**Comment by steckmey** [comment]
@Overload119 thank you, you saved me a lot of time!
I think this should be prominently featured on the install notes. Better yet, Added to the script.

**Comment by tupton** [comment]
Sorry for the astronomical, epochal delay on this. I made a [new release](https://github.com/tupton/alfred-chrome-history/releases/tag/0.5.0) that should fix these issues, including updating `alfred.py` and getting the workflow to work properly from the release and from the cloned repository.

I no longer use Chrome or this workflow, but I will respond to issues and try to fix them, hopefully without a multi-year delay next time.
